"""
course_output/holes.py

Hole routing export -- holes.json (course/CourseDescription_nodes/holes.json).

Deliberately a separate module/CLI step from splines.py -- holes.json
is a completely different schema (routing waypoints + par/tee/pin
metadata, not a spline shape), and letting it be regenerated
independently from splines and terrain (see PGA2k_gen.py's
step_write_holes) means tweaking mask settings here doesn't force
redoing either of those.

Conversion from OSM "hole" ways follows Chad's TGC-Designer-Tools
(OSMTGC.py's newHole()) exactly: waypoint reduction/expansion to
exactly 3 points ([first, second, last] if more than 3 -- not an
even resample), y always 0.0 (the game appears to snap these to
actual terrain height on load, so Chad's tool never bothers sampling
real elevation for them either), teePositions holds just the first
(possibly-reduced) point, and pinPositions stays at the template
default -- Chad's own tool never sets it from OSM data either, OSM
has no pin-location concept for a hole. creatorDefinedPar carries the
OSM "par" tag; "par" itself stays at the template default of 4 --
this looks like a mismatch at first (par tag ignored?), but it's
exactly what Chad's actual code does, not an approximation of it.

Holes are ordered by OSM's "ref" tag (parsed as int); missing/zero
falls back to sequential assignment in discovery order, matching
Chad's own hole_dictionary logic -- including its own minor asymmetry
(a missing ref parses to -1 and is used as a dictionary key directly,
which could collide if multiple holes lack a ref tag, while ref="0"
specifically triggers auto-assignment). Reproduced faithfully rather
than "fixed", since the point here is matching Chad's tool, not
improving on it.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Optional

from ingest.osm import Feature
from course_output.userLayers import GRID_ORIGIN_OFFSET

_HOLE_JSON_TEMPLATE = {
    "waypoints": [],
    "teePositions": [],
    "pinPositions": [{"x": 0.0, "y": 0.0, "z": 0.0}],
    "greenRadius": 0.0,
    "teeRadius": 0.0,
    "fairwayRadius": 0.0,
    "fairwayStart": 0.0,
    "fairwayEnd": 0.0,
    "fairwayNoiseScale": -1.0,
    "roughRadius": 0.0,
    "heavyRoughRadius": 0.0,
    "hazardGreenCount": 0.0,
    "hazardFairwayCount": 0.0,
    "hazardFairwayPeriod": -1.0,
    "teeHeight": -1.0,
    "greenSeed": 206208328,
    "fairwaySeed": 351286870,
    "teeTexture": -1,
    "creatorDefinedPar": -1,
    "name": "",
    "flagOffset": {"x": 0.0, "y": 0.0},
    "par": 4,
}


def _waypoint3d(x: float, y: float, z: float) -> dict:
    return {"x": x, "y": y, "z": z}


def _add_halfway_point(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    """Chad's addHalfwayPoint: for an autogenerated 2-point (tee, green) routing, insert a midpoint."""
    first, last = points[0], points[-1]
    mid = ((first[0] + last[0]) / 2.0, (first[1] + last[1]) / 2.0)
    return [first, mid, last]


def new_hole(userpar: int, points: list[tuple[float, float]]) -> Optional[dict]:
    """
    Build one holes.json entry from a hole's routing points (x, z) --
    equivalent to Chad's TGC-Designer-Tools OSMTGC.py newHole().

    Returns None if points has fewer than 2 entries (matching Chad's
    own "minimum needed points" check) -- not enough to route a hole.
    """
    hole = copy.deepcopy(_HOLE_JSON_TEMPLATE)
    hole["creatorDefinedPar"] = userpar

    if len(points) < 2:
        return None
    elif len(points) == 2:
        points = _add_halfway_point(points)
    elif len(points) > 3:
        # Game only supports start point, waypoint, and endpoint --
        # Chad's tool takes literally [first, second, last], not an
        # even resample across the original point count.
        points = [points[0], points[1], points[-1]]

    for p in points:
        hole["waypoints"].append(_waypoint3d(p[0], 0.0, p[1]))

    hole["teePositions"].append(_waypoint3d(points[0][0], 0.0, points[0][1]))
    return hole


def build_holes(features: list[Feature]) -> list[dict]:
    """
    Build the ordered holes.json list from every "hole" Feature with
    mask=False (i.e. NOT excluded -- see ingest/osm.py's Feature
    docstring). mask=True holes (e.g. a duplicate bleeding in from a
    neighboring course on the same OSM map) are skipped entirely --
    this is exactly the "can't export more than 18 holes" constraint
    the mask scheme exists to let you work around.
    """
    hole_dict: dict[int, dict] = {}
    for f in features:
        if f.kind != "hole" or f.mask:
            continue

        try:
            userpar = int(f.tags.get("par", -1))
        except (TypeError, ValueError):
            userpar = -1
        try:
            hole_num = int(f.tags.get("ref", -1))
        except (TypeError, ValueError):
            hole_num = -1

        # Same offset userLayers.py applies to terrain stamps and
        # splines.py now applies to splines -- PGA's grid is centered
        # on the origin ([-1000, 1000] for a 2000 m course), not
        # [0, 2000] like our local frame. Without this, hole waypoints
        # would be off by +1000 in both x and z, same bug as splines.
        points = [(x - GRID_ORIGIN_OFFSET, z - GRID_ORIGIN_OFFSET) for x, z in f.geometry.coords]
        hole = new_hole(userpar, points)
        if hole is None:
            continue

        if hole_num == 0:
            hole_num = len(hole_dict) + 1
        hole_dict[hole_num] = hole

    return [hole_dict[key] for key in sorted(hole_dict)]


def save_holes(holes: list[dict], path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        json.dump(holes, f, indent=2)
